apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextapp
  namespace: myapp
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextapp
  namespace: myapp
subjects:
  - kind: ServiceAccount
    name: nextapp
roleRef:
  kind: Role
  name: nextapp
  apiGroup: rbac.authorization.k8s.io
