apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }} 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        {{ .Values.labels.app  }}
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
