apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: {{ .Values.name }} 
  minReplicas: {{ .Values.hpa.minReplica }} 
  maxReplicas: {{ .Values.hpa.maxReplica }} 
  metrics: 
  - type: Resource
    resource:
      name: {{ .Values.hpa.targetResource.name }}  
      target:
        type: {{ .Values.hpa.targetResource.type }}
        averageValue: {{ .Values.hpa.targetResource.value }}